version: '3.8'

services:
  admin-panel:
    build: .
    container_name: willowe_admin_panel
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MAIN_APP_URL: http://46.62.131.90:3000
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: qwe
    volumes:
      - ./logs:/app/logs
    networks:
      - admin-network

networks:
  admin-network:
    driver: bridge 